ALTER TABLE tag DROP COLUMN normalized_name;
ALTER TABLE tag ADD COLUMN normalized_name VARCHAR(100) GENERATED ALWAYS AS (LOWER(name)) STORED;

INSERT INTO tag (name, category, created_by_type, moderation_status, is_active)
VALUES
    ('HTML', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('CSS', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Vue', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Angular', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Node.js', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Express', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('NestJS', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Django', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('FastAPI', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Flask', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Hibernate', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Kafka', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Redis', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('MongoDB', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('MySQL', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('REST API', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('GraphQL', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('JUnit', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Mockito', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('CI/CD', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Docker Compose', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Nginx', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Postman', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Selenium', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Cypress', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Pandas', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('NumPy', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('PyTorch', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('TensorFlow', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Figma', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Manual Testing', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('UI/UX', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Android', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('iOS', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Swift', 'TECH', 'SYSTEM', 'APPROVED', TRUE),
    ('Product Management', 'DIRECTION', 'SYSTEM', 'APPROVED', TRUE),
    ('System Analysis', 'DIRECTION', 'SYSTEM', 'APPROVED', TRUE),
    ('Cybersecurity', 'DIRECTION', 'SYSTEM', 'APPROVED', TRUE),
    ('Game Development', 'DIRECTION', 'SYSTEM', 'APPROVED', TRUE)
ON CONFLICT (name, category) DO NOTHING;
