server:
  port: 8081

spring:
  application:
    name: opportunity

  datasource:
    url: jdbc:postgresql://localhost:5432/opportunity_db
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
